"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_router_dom_1 = require("react-router-dom");
var PrivacyPolicy = function () {
    return (React.createElement("div", null,
        React.createElement("h1", null, "Synergy Privacy Policy"),
        React.createElement("p", null, "Last Revised: 23 November, 2019"),
        React.createElement("p", null, "Our privacy policy applies to information we collect when you use or access our website, application, or just interact with us. We may change this privacy policy from time to time. Whenever we make changes to this privacy policy, the changes are effective one week after we post the revised privacy policy (as indicated by revising the date at the top of our privacy policy). We encourage you to review our privacy policy whenever you access our services to stay informed about our information practices and the ways you can help protect your privacy."),
        React.createElement("hr", null),
        React.createElement("h2", null, "Collection of Information"),
        React.createElement("h4", null, "Information You Provide to Us"),
        React.createElement("p", null, "We collect information you provide directly to us. For example, we collect information when you participate in any interactive features of our services, fill out a form, request customer support, provide any contact or identifying information or otherwise communicate with us. The types of information we may collect include your name, email address, and other contact or identifying information you choose to provide."),
        React.createElement("h4", null, "Information We Collect Automatically When You Use the Services"),
        React.createElement("p", null, "When you access or use our services, we automatically collect information about you, including:"),
        React.createElement("ul", { className: "ml-5" },
            React.createElement("li", null, "Log Information: We log information about your use of our services, including the type of browser you use, access times, and pages viewed."),
            React.createElement("li", null, "Information Collected by Cookies: We use various technologies to collect information, and this may include sending cookies to your computer. Cookies are small data files stored on your hard drive or in your device memory that helps us to improve our services and your experience, see which areas and features of our services are popular and count visits.")),
        React.createElement("h4", null, "Information We Collect From Other Sources"),
        React.createElement("p", null, "In order to provide you with access to the Service, or to provide you with better service in general, we may combine information obtained from other sources (for example, a third-party service whose application you have authorized or used to sign in) and combine that with information we collect through our services."),
        React.createElement("hr", null),
        React.createElement("h2", null, "Use of Information"),
        React.createElement("p", null, "We use information about you for various purposes, including to:"),
        React.createElement("ul", { className: "ml-5" },
            React.createElement("li", null, "Provide, maintain and improve our services;"),
            React.createElement("li", null, "Provide services you request and to send you related information;"),
            React.createElement("li", null, "Send you technical notices, updates, security alerts and support and administrative messages;"),
            React.createElement("li", null, "Respond to your comments, questions and requests and provide customer service;"),
            React.createElement("li", null, "Communicate with you about news and information related to our service;"),
            React.createElement("li", null, "Monitor and analyze trends, usage and activities in connection with our services; and"),
            React.createElement("li", null, "Personalize and improve our services.")),
        React.createElement("p", null, "By accessing and using our services, you consent to the processing and transfer of your information in and to the United States and other countries."),
        React.createElement("hr", null),
        React.createElement("h2", null, "Sharing of Information"),
        React.createElement("p", null, "We may share personal information about you as follows:"),
        React.createElement("ul", { className: "ml-5" },
            React.createElement("li", null, "If we believe disclosure is reasonably necessary to comply with any applicable law, regulation, legal process or governmental request;"),
            React.createElement("li", null,
                "To enforce applicable user agreements or policies, including our ",
                React.createElement(react_router_dom_1.Link, { to: "/terms-of-service" }, "Terms of Service"),
                "; and to protect us, our users or the public from harm or illegal activities;")),
        React.createElement("p", null, "We may also share aggregated or anonymized information that does not directly identify you ONLY FOR RESEARCH PURPOSES."),
        React.createElement("hr", null),
        React.createElement("h2", null, "Security"),
        React.createElement("p", null, "We take reasonable measures to help protect personal information from loss, theft, misuse and unauthorized access, disclosure, alteration and destruction."),
        React.createElement("hr", null),
        React.createElement("h2", null, "Your Information Choices"),
        React.createElement("h4", null, "Location Information"),
        React.createElement("p", null, "We never collect and store your location information."),
        React.createElement("h4", null, "Cookies"),
        React.createElement("p", null, "Most web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove or reject browser cookies. Please note that if you choose to remove or reject cookies, this could affect the availability and functionality of our services."),
        React.createElement("hr", null),
        React.createElement("h2", null, "Promotional Communications"),
        React.createElement("p", null, "Synergy never carris out promotional activities. You will never receive any promotional emails from us."),
        React.createElement("hr", null),
        React.createElement("h2", null, "Contact Us"),
        React.createElement("p", null, "Questions or comments about the Service may be directed to us at the email address synergylearn@gmail.com.")));
};
exports.default = PrivacyPolicy;
//# sourceMappingURL=PrivacyPolicy.js.map